// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJECT_C_.Data;

#nullable disable

namespace PROJECT_C_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130032725_UpdateCoordinates")]
    partial class UpdateCoordinates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROJECT_C_.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Traditional Vietnamese beef noodle soup",
                            Latitude = 10.776889000000001,
                            Longitude = 106.700806,
                            Name = "Pho Bo",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vietnamese baguette sandwich",
                            Latitude = 10.762622,
                            Longitude = 106.660172,
                            Name = "Banh Mi",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Broken rice with grilled pork",
                            Latitude = 10.792375,
                            Longitude = 106.691689,
                            Name = "Com Tam",
                            Price = 50000m
                        });
                });

            modelBuilder.Entity("PROJECT_C_.Models.FoodTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodTranslations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Phở bò truyền thống Việt Nam",
                            FoodId = 1,
                            LanguageCode = "vi-VN",
                            Name = "Phở Bò"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Traditional Vietnamese beef noodle soup",
                            FoodId = 1,
                            LanguageCode = "en-US",
                            Name = "Beef Pho"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bánh mì Việt Nam",
                            FoodId = 2,
                            LanguageCode = "vi-VN",
                            Name = "Bánh Mì"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Vietnamese baguette sandwich",
                            FoodId = 2,
                            LanguageCode = "en-US",
                            Name = "Vietnamese Baguette"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cơm tấm sườn nướng",
                            FoodId = 3,
                            LanguageCode = "vi-VN",
                            Name = "Cơm Tấm"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Broken rice with grilled pork",
                            FoodId = 3,
                            LanguageCode = "en-US",
                            Name = "Broken Rice"
                        });
                });

            modelBuilder.Entity("PROJECT_C_.Models.FoodTranslation", b =>
                {
                    b.HasOne("PROJECT_C_.Models.Food", "Food")
                        .WithMany("Translations")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("PROJECT_C_.Models.Food", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
