namespace NarrationApp.Mobile.Features.Home;

public sealed record VisitorUiText(
    string PageTitle,
    string HeaderSettingsTitle,
    string TabMap,
    string TabTours,
    string TabDiscover,
    string TabMe,
    string WelcomeTitlePrefix,
    string WelcomeDescription,
    string FeatureAutoPlayTitle,
    string FeatureAutoPlayBody,
    string FeatureLanguageTitle,
    string FeatureLanguageBody,
    string FeatureTourTitle,
    string FeatureTourBody,
    string StartExploringButton,
    string LanguageTitle,
    string LanguageDescription,
    string ContinueButton,
    string LocationPermissionTitle,
    string LocationPermissionDescription,
    string EnableLocationButton,
    string NotificationEyebrow,
    string NotificationTitle,
    string CloseButton,
    string NoNotificationsTitle,
    string NoNotificationsDescription,
    string SavedDataModeLabel,
    string ClearDirectionsButton,
    string CenterOnUserLabel,
    string HideButton,
    string DirectionsButton,
    string DetailButton,
    string ListenNowButton,
    string GeofenceRadiusLabel,
    string PriorityLabel,
    string AudioStatusLabel,
    string LanguageCountFormat,
    string NearbyPoiPrefix,
    string DiscoverTitle,
    string DiscoverSubtitle,
    string ChangeLanguageLabel,
    string RefreshDataLabel,
    string SearchPlaceholder,
    string SearchHint,
    string EmptyPoiTitle,
    string EmptyPoiDescription,
    string FeaturedPoiEyebrow,
    string PriorityStatLabel,
    string AudioFilesStatLabel,
    string SupportedLanguagesStatLabel,
    string NarrationLabel,
    string FullscreenButton,
    string ContentLabel,
    string StoryAtStopTitle,
    string TranscriptQuickTitle,
    string RelatedLabel,
    string RelatedTitle,
    string RelatedEmptyTitle,
    string RelatedEmptyDescription,
    string MapButton,
    string PauseNarrationButton,
    string ListenNarrationButton,
    string FullPlayerDescription,
    string HideTranscriptButton,
    string TranscriptButton,
    string LanguagePickerAriaLabel,
    string LanguagePickerTitle,
    string LanguagePickerDescription,
    string LanguagePickerEmpty,
    string CurrentDeviceLabel,
    string AppLanguageLabel,
    string AppLanguageDescription,
    string SettingsLanguageSelectLabel,
    string AudioSettingsTitle,
    string GpsSettingsTitle,
    string ContentAudioCacheTitle,
    string ListenHistoryTitle,
    string AboutAppTitle)
{
    public string FormatLanguageCount(int count) =>
        string.Format(LanguageCountFormat, count);
}

public static class VisitorUiTextCatalog
{
    public static readonly IReadOnlySet<string> SupportedAppLanguageCodes =
        new HashSet<string>(new[] { "vi", "en" }, StringComparer.OrdinalIgnoreCase);

    private static readonly VisitorUiText Vietnamese = new(
        "Đa thuyết minh ẩm thực Vĩnh Khánh",
        "Cài đặt",
        "Bản đồ",
        "Tour",
        "Khám phá",
        "Tôi",
        "Chào mừng đến",
        "Khám phá các điểm tham quan với thuyết minh tự động đa ngôn ngữ. Chỉ cần đi bộ, chúng tôi sẽ kể cho bạn nghe.",
        "Tự động phát",
        "khi đến gần điểm tham quan",
        "Ngôn ngữ app",
        "chỉ đổi giao diện Việt / Anh, thuyết minh vẫn đa ngôn ngữ",
        "Tour có sẵn",
        "lộ trình khám phá được vạch sẵn",
        "Bắt đầu khám phá ->",
        "Chọn ngôn ngữ",
        "Chọn ngôn ngữ giao diện ứng dụng. Phần thuyết minh vẫn có thể đổi sang các ngôn ngữ khác khi nghe.",
        "Tiếp tục ->",
        "Cho phép truy cập vị trí",
        "Để tự động phát thuyết minh khi bạn đến gần điểm tham quan, ứng dụng cần truy cập GPS của bạn.",
        "Cho phép vị trí",
        "Thông báo",
        "Cập nhật gần đây",
        "Đóng",
        "Chưa có thông báo mới",
        "Khi có POI gần bạn, tour mới hoặc cập nhật từ API, thông báo sẽ xuất hiện ở đây.",
        "Dữ liệu đã lưu",
        "Tắt dẫn đường",
        "Về vị trí của tôi",
        "Ẩn",
        "Dẫn tới đây",
        "Xem chi tiết",
        "Nghe ngay",
        "Bán kính",
        "Ưu tiên",
        "Audio thuyết minh",
        "{0} ngôn ngữ",
        "Đang ở gần",
        "Khám phá",
        "Tất cả điểm tham quan gần bạn",
        "Đổi ngôn ngữ",
        "Làm mới dữ liệu",
        "Tìm theo tên, danh mục...",
        "Tìm",
        "Chưa có điểm phù hợp bộ lọc hiện tại.",
        "Thử đổi từ khóa hoặc chọn danh mục khác.",
        "Điểm tham quan nổi bật",
        "Mức ưu tiên",
        "Audio thuyết minh",
        "Hỗ trợ",
        "Thuyết minh",
        "Toàn màn",
        "Nội dung",
        "Câu chuyện tại điểm dừng",
        "Bản thuyết minh xem nhanh",
        "Liên quan",
        "Điểm tham quan gần phong cách này",
        "Chưa có POI liên quan phù hợp.",
        "Tiếp tục dùng tab Khám phá để xem thêm các điểm gần bạn.",
        "Bản đồ",
        "Tạm dừng thuyết minh",
        "Nghe thuyết minh",
        "Nghe thuyết minh toàn màn hình với transcript đồng bộ và thao tác nhanh.",
        "Ẩn transcript",
        "Transcript",
        "Chọn ngôn ngữ thuyết minh",
        "Chọn ngôn ngữ",
        "Chỉ hiển thị ngôn ngữ đã có audio cho POI này",
        "Chưa có ngôn ngữ audio khả dụng.",
        "Thiết bị hiện tại",
        "Ngôn ngữ ứng dụng",
        "Giao diện app chỉ đổi giữa Tiếng Việt và English; audio thuyết minh vẫn hỗ trợ nhiều ngôn ngữ.",
        "Chọn ngôn ngữ ứng dụng",
        "Audio & thuyết minh",
        "Vị trí & GPS",
        "Cache nội dung & audio",
        "Lịch sử nghe",
        "Về ứng dụng");

    private static readonly VisitorUiText English = new(
        "Vinh Khanh Food Narration",
        "Settings",
        "Map",
        "Tour",
        "Discover",
        "Me",
        "Welcome to",
        "Explore nearby food stops with automatic multilingual narration. Just walk around and we will tell the story.",
        "Auto play",
        "when you enter a POI radius",
        "App language",
        "switches only Vietnamese / English UI, while narration stays multilingual",
        "Ready-made tours",
        "curated routes for quick exploration",
        "Start exploring ->",
        "Choose language",
        "Choose the app interface language. Narration can still switch to other languages while listening.",
        "Continue ->",
        "Allow location access",
        "To play narration automatically near a place, the app needs access to your GPS.",
        "Allow location",
        "Notifications",
        "Recent updates",
        "Close",
        "No new notifications",
        "Nearby POIs, new tours, and API updates will appear here.",
        "Saved data mode",
        "Stop directions",
        "Back to my location",
        "Hide",
        "Take me there",
        "View details",
        "Listen now",
        "Radius",
        "Priority",
        "Narration audio",
        "{0} languages",
        "Near",
        "Discover",
        "All nearby points of interest",
        "Change language",
        "Refresh data",
        "Search by name or category...",
        "Search",
        "No POIs match the current filter.",
        "Try another keyword or category.",
        "Featured point of interest",
        "Priority level",
        "Narration audio",
        "Supported",
        "Narration",
        "Full screen",
        "Content",
        "Story at this stop",
        "Quick transcript",
        "Related",
        "Nearby places with a similar style",
        "No related POIs yet.",
        "Keep using Discover to find more nearby places.",
        "Map",
        "Pause narration",
        "Listen narration",
        "Listen in full screen with synced transcript and quick controls.",
        "Hide transcript",
        "Transcript",
        "Choose narration language",
        "Choose language",
        "Only languages with audio for this POI are shown",
        "No audio language is available yet.",
        "Current device",
        "App language",
        "The app interface switches only between Vietnamese and English; narration audio remains multilingual.",
        "Choose app language",
        "Audio & narration",
        "Location & GPS",
        "Content & audio cache",
        "Listening history",
        "About app");

    public static VisitorUiText ForLanguage(string? languageCode) =>
        string.Equals(Normalize(languageCode), "en", StringComparison.OrdinalIgnoreCase) ? English : Vietnamese;

    public static bool IsSupportedAppLanguage(string? languageCode) =>
        SupportedAppLanguageCodes.Contains(Normalize(languageCode));

    private static string Normalize(string? languageCode)
    {
        if (string.IsNullOrWhiteSpace(languageCode))
        {
            return "vi";
        }

        var trimmed = languageCode.Trim().ToLowerInvariant();
        var separatorIndex = trimmed.IndexOfAny(['-', '_']);
        return separatorIndex > 0 ? trimmed[..separatorIndex] : trimmed;
    }
}
