// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJECT_C_.Data;

#nullable disable

namespace PROJECT_C_.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127115815_SeedFoodData")]
    partial class SeedFoodData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PROJECT_C_.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Traditional Vietnamese beef noodle soup",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Pho Bo",
                            Price = 45000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Vietnamese baguette sandwich",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Banh Mi",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Broken rice with grilled pork",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Name = "Com Tam",
                            Price = 50000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
