// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NarrationApp.Server.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NarrationApp.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416175527_AddOwnerRegistrationFlow")]
    partial class AddOwnerRegistrationFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("preferred_language");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_app_users_role_id");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.AudioAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer")
                        .HasColumnName("poi_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer")
                        .HasColumnName("source_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_audio_assets");

                    b.HasIndex("PoiId", "LanguageCode", "SourceType")
                        .IsUnique()
                        .HasDatabaseName("ix_audio_assets_poi_id_language_code_source_type");

                    b.ToTable("audio_assets", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Geofence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown_seconds");

                    b.Property<int>("DebounceSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("debounce_seconds");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("NearestOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("nearest_only");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer")
                        .HasColumnName("poi_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("radius_meters");

                    b.Property<string>("TriggerAction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger_action");

                    b.HasKey("Id")
                        .HasName("pk_geofences");

                    b.HasIndex("PoiId")
                        .HasDatabaseName("ix_geofences_poi_id");

                    b.ToTable("geofences", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.ModerationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_note");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_moderation_requests");

                    b.HasIndex("RequestedBy")
                        .HasDatabaseName("ix_moderation_requests_requested_by");

                    b.HasIndex("ReviewedBy")
                        .HasDatabaseName("ix_moderation_requests_reviewed_by");

                    b.HasIndex("EntityType", "EntityId", "Status")
                        .HasDatabaseName("ix_moderation_requests_entity_type_entity_id_status");

                    b.ToTable("moderation_requests", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("ix_notifications_user_id_is_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<string>("MapLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("map_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("NarrationMode")
                        .HasColumnType("integer")
                        .HasColumnName("narration_mode");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slug");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_pois");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_pois_owner_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_pois_slug");

                    b.ToTable("pois", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.PoiTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Highlight")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("highlight");

                    b.Property<bool>("IsFallback")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fallback");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer")
                        .HasColumnName("poi_id");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("story");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_poi_translations");

                    b.HasIndex("PoiId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_poi_translations_poi_id_language_code");

                    b.ToTable("poi_translations", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.QrCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("LocationHint")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("location_hint");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.HasKey("Id")
                        .HasName("pk_qr_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_qr_codes_code");

                    b.ToTable("qr_codes", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cover_image");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_minutes");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_tours");

                    b.ToTable("tours", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.TourSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CurrentStopSequence")
                        .HasColumnType("integer")
                        .HasColumnName("current_stop_sequence");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TourId")
                        .HasColumnType("integer")
                        .HasColumnName("tour_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tour_sessions");

                    b.HasIndex("TourId")
                        .HasDatabaseName("ix_tour_sessions_tour_id");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("ix_tour_sessions_user_id_updated_at");

                    b.HasIndex("UserId", "TourId", "Status")
                        .HasDatabaseName("ix_tour_sessions_user_id_tour_id_status");

                    b.ToTable("tour_sessions", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.TourStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PoiId")
                        .HasColumnType("integer")
                        .HasColumnName("poi_id");

                    b.Property<int>("RadiusMeters")
                        .HasColumnType("integer")
                        .HasColumnName("radius_meters");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int>("TourId")
                        .HasColumnType("integer")
                        .HasColumnName("tour_id");

                    b.HasKey("Id")
                        .HasName("pk_tour_stops");

                    b.HasIndex("PoiId")
                        .HasDatabaseName("ix_tour_stops_poi_id");

                    b.HasIndex("TourId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_tour_stops_tour_id_sequence");

                    b.ToTable("tour_stops", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.VisitEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("device_id");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<int>("ListenDurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("listen_duration_seconds");

                    b.Property<double?>("Lng")
                        .HasColumnType("double precision")
                        .HasColumnName("lng");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer")
                        .HasColumnName("poi_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_visit_events");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_visit_events_user_id");

                    b.HasIndex("PoiId", "CreatedAt")
                        .HasDatabaseName("ix_visit_events_poi_id_created_at");

                    b.ToTable("visit_events", (string)null);
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.AppUser", b =>
                {
                    b.HasOne("NarrationApp.Server.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.AudioAsset", b =>
                {
                    b.HasOne("NarrationApp.Server.Data.Entities.Poi", "Poi")
                        .WithMany("AudioAssets")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audio_assets_pois_poi_id");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Geofence", b =>
                {
                    b.HasOne("NarrationApp.Server.Data.Entities.Poi", "Poi")
                        .WithMany("Geofences")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_geofences_pois_poi_id");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.ModerationRequest", b =>
                {
                    b.HasOne("NarrationApp.Server.Data.Entities.AppUser", "RequestedByUser")
                        .WithMany("RequestedModerationRequests")
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_moderation_requests_app_users_requested_by");

                    b.HasOne("NarrationApp.Server.Data.Entities.AppUser", "ReviewedByUser")
                        .WithMany("ReviewedModerationRequests")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_moderation_requests_app_users_reviewed_by");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Notification", b =>
                {
                    b.HasOne("NarrationApp.Server.Data.Entities.AppUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_app_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Poi", b =>
                {
                    b.HasOne("NarrationApp.Server.Data.Entities.AppUser", "Owner")
                        .WithMany("OwnedPois")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pois_app_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.PoiTranslation", b =>
                {
                    b.HasOne("NarrationApp.Server.Data.Entities.Poi", "Poi")
                        .WithMany("Translations")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poi_translations_pois_poi_id");

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.TourSession", b =>
                {
                    b.HasOne("NarrationApp.Server.Data.Entities.Tour", "Tour")
                        .WithMany()
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tour_sessions_tours_tour_id");

                    b.HasOne("NarrationApp.Server.Data.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tour_sessions_app_users_user_id");

                    b.Navigation("Tour");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.TourStop", b =>
                {
                    b.HasOne("NarrationApp.Server.Data.Entities.Poi", "Poi")
                        .WithMany("TourStops")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tour_stops_pois_poi_id");

                    b.HasOne("NarrationApp.Server.Data.Entities.Tour", "Tour")
                        .WithMany("Stops")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tour_stops_tours_tour_id");

                    b.Navigation("Poi");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.VisitEvent", b =>
                {
                    b.HasOne("NarrationApp.Server.Data.Entities.Poi", "Poi")
                        .WithMany("VisitEvents")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_visit_events_pois_poi_id");

                    b.HasOne("NarrationApp.Server.Data.Entities.AppUser", "User")
                        .WithMany("VisitEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_visit_events_app_users_user_id");

                    b.Navigation("Poi");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.AppUser", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("OwnedPois");

                    b.Navigation("RequestedModerationRequests");

                    b.Navigation("ReviewedModerationRequests");

                    b.Navigation("VisitEvents");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Poi", b =>
                {
                    b.Navigation("AudioAssets");

                    b.Navigation("Geofences");

                    b.Navigation("TourStops");

                    b.Navigation("Translations");

                    b.Navigation("VisitEvents");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NarrationApp.Server.Data.Entities.Tour", b =>
                {
                    b.Navigation("Stops");
                });
#pragma warning restore 612, 618
        }
    }
}
